services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8800:8800"
    environment:
      DB_HOST: book-project-db.cl1dqjwy3tlq.us-east-1.rds.amazonaws.com  # RDS endpoint
      DB_USER: admin                    # RDS master user
      DB_PASSWORD: password             # RDS password
      DB_NAME: bookdb                   # RDS DB name

