services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    environment:
      VITE_BOOK_APP_API_BASE_URL: ${BOOK_APP_API_BASE_URL}  # Backend URL in prod env (use domain name)

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8800:8800"
    environment:
      DB_HOST: ${DB_HOST}  # RDS endpoint
      DB_USER: ${DB_USER}  # RDS master user
      DB_PASSWORD: ${DB_PASSWORD}       # RDS password
      DB_NAME: ${DB_NAME}               # RDS DB name

