services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8800:8800"
    environment:
      DB_HOST: ${DB_HOST}  # RDS endpoint
      DB_USER: ${DB_USER}  # RDS master user
      DB_PASSWORD: ${DB_PASSWORD}       # RDS password
      DB_NAME: ${DB_NAME}               # RDS DB name

